const { createClient } = require('@supabase/supabase-js');

const stagingClient = createClient(
  'https://hieokzpxehyelhbubbpb.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpZW9renB4ZWh5ZWxoYnViYnBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NTU1ODQsImV4cCI6MjA3ODAzMTU4NH0.NDXes_vCvs9ocgJcc4BXqFXe68SUjRkBz_wEqvprLVo'
);

async function createBasicSchema() {
  console.log('🏗️ Creating basic schema in staging...\n');

  try {
    // Create projects table (most important)
    console.log('📋 Creating projects table...');
    const { error: projectsError } = await stagingClient.rpc('exec_sql', {
      sql: `
        CREATE TABLE IF NOT EXISTS public.projects (
          id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          created_at timestamp with time zone DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
          name text,
          owner text,
          manager text,
          status text,
          qbid text,
          stage_id bigint,
          sharepoint_folder_url text,
          contract_amount numeric
        );
        
        CREATE INDEX IF NOT EXISTS projects_qbid_idx ON public.projects (qbid);
        CREATE INDEX IF NOT EXISTS projects_stage_id_idx ON public.projects (stage_id);
      `,
    });

    if (projectsError) {
      console.log('⚠️ Projects table:', projectsError.message);
    } else {
      console.log('✅ Projects table created');
    }

    // Create users table
    console.log('👥 Creating users table...');
    const { error: usersError } = await stagingClient.rpc('exec_sql', {
      sql: `
        CREATE TABLE IF NOT EXISTS public.users (
          id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          created_at timestamp with time zone DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
          name text,
          email text UNIQUE,
          role text DEFAULT 'user',
          auth_user_id uuid
        );
        
        CREATE INDEX IF NOT EXISTS users_email_idx ON public.users (email);
        CREATE INDEX IF NOT EXISTS users_auth_user_id_idx ON public.users (auth_user_id);
      `,
    });

    if (usersError) {
      console.log('⚠️ Users table:', usersError.message);
    } else {
      console.log('✅ Users table created');
    }

    console.log('\n🎉 Basic schema created!');
    console.log('🔧 You can now copy data with: node quick-copy.js');
  } catch (err) {
    console.error('💥 Schema creation failed:', err.message);
    console.log(
      '\n💡 Alternative: Copy schema manually from Supabase dashboard'
    );
    console.log('📍 Production: https://groxqyaoavmfvmaymhbe.supabase.co');
    console.log('📍 Staging: https://hieokzpxehyelhbubbpb.supabase.co');
  }
}

createBasicSchema();
