#!/usr/bin/env python3
"""
Generate SQL migration to import prospects from CSV with trade breakdowns
Usage: python generate-prospects-import.py > db/migrations/2025-11-09-import-all-prospects.sql
"""

import csv
import sys
from pathlib import Path

# CSV file path - check multiple locations
csv_locations = [
    Path(__file__).parent / "import prospects.csv",
    Path("C:/Users/WesGray/OneDrive - Floors Unlimited USA/import prospects.csv"),
    Path(__file__).parent.parent.parent / "import prospects.csv"
]

csv_path = None
for loc in csv_locations:
    if loc.exists():
        csv_path = loc
        break

if not csv_path:
    print("Error: Could not find 'import prospects.csv'", file=sys.stderr)
    print("Searched:", file=sys.stderr)
    for loc in csv_locations:
        print(f"  - {loc}", file=sys.stderr)
    sys.exit(1)

def clean_currency(value):
    """Convert currency string to numeric or NULL"""
    if not value or value.strip() in ('', '-', ' - '):
        return 'NULL'
    clean = value.replace(',', '').replace('$', '').replace(' ', '').strip()
    try:
        return str(float(clean))
    except:
        return 'NULL'

def map_pipeline_status(status):
    """Map CSV status to our enum"""
    mapping = {
        'Landed': 'won',
        'Probable': 'verbal_commit',
        'Questionable': 'proposal_sent',
        'Doubtful': 'qualified',
    }
    return mapping.get(status, 'lead')

def map_probability(prob):
    """Extract probability percentage"""
    if not prob or prob.strip() == '':
        return 'NULL'
    return prob.replace('%', '').strip()

def escape_sql(value):
    """Escape single quotes for SQL"""
    if not value:
        return ''
    return value.replace("'", "''")

# Trade code mapping to match CSV columns
trade_columns = {
    '06 61 13': '06.61.13',
    '09 30 00': '09.30.00', 
    '09 64 00': '09.64.00',
    '09 65 00': '09.65.00',
    '09 68 00': '09.68.00',
    '10 28 13': '10.28.00',  # Bathroom Accessories
    '10 28 19': '10.28.00',  # Also Bathroom Accessories (cubicles)
    '12 36 00': '12.36.00',
    '22 40 00': '22.40.00'
}

# Generate SQL
print("""-- Migration: Import all prospects from CSV with trade breakdowns
-- Date: 2025-11-09
-- Purpose: Bulk import prospects and link them to trades
-- Generated by: generate-prospects-import.py

BEGIN;

-- Helper functions
CREATE OR REPLACE FUNCTION map_pipeline_status(csv_status TEXT)
RETURNS pipeline_status AS $$
BEGIN
  RETURN CASE 
    WHEN csv_status = 'Landed' THEN 'won'
    WHEN csv_status = 'Probable' THEN 'verbal_commit'
    WHEN csv_status = 'Questionable' THEN 'proposal_sent'
    WHEN csv_status = 'Doubtful' THEN 'qualified'
    ELSE 'lead'
  END;
END;
$$ LANGUAGE plpgsql;

-- Temp table to store engagement IDs for trade linking
CREATE TEMP TABLE imported_engagements (
  temp_id SERIAL PRIMARY KEY,
  engagement_id UUID,
  row_number INTEGER
);
""")

with open(csv_path, 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    rows = list(reader)
    
    # Skip the total row
    rows = [r for r in rows if r['Project'] != 'Total']
    
    print("\n-- Insert prospects")
    print("INSERT INTO public.engagements (")
    print("  type, name, customer_id, pipeline_status, probability,")
    print("  bid_amount, lead_source, manager, owner, notes, created_at")
    print(") VALUES")
    
    for i, row in enumerate(rows):
        project_name = escape_sql(row['Project'])
        customer_name = escape_sql(row['Customer'])
        contact = escape_sql(row['Contact'])
        pm = escape_sql(row['Project Manager'])
        architect = escape_sql(row['Architect/Designer'])
        sales_owner = escape_sql(row['Sales'])
        bid_date = row['Bid Date']
        last_call = row['Last Call']
        pipeline_status = map_pipeline_status(row['Pipeline Status'])
        probability = map_probability(row['Probability'])
        revenue_est = clean_currency(row['Revenue Est.'])
        
        # Build notes field
        notes_parts = []
        if contact:
            notes_parts.append(f"Contact: {contact}")
        if pm:
            notes_parts.append(f"PM: {pm}")
        if architect:
            notes_parts.append(f"Architect: {architect}")
        if bid_date:
            notes_parts.append(f"Bid Date: {bid_date}")
        if last_call:
            notes_parts.append(f"Last Call: {last_call}")
        
        notes = escape_sql(' | '.join(notes_parts))
        
        # Determine lead source
        if architect and architect.lower() != 'na':
            lead_source = 'architect'
        elif customer_name:
            lead_source = 'gc_relationship'
        else:
            lead_source = 'other'
        
        # Use bid date or created_at default
        created_at = f"'{bid_date}'" if bid_date else 'CURRENT_DATE'
        
        comma = ',' if i < len(rows) - 1 else ';'
        
        print(f"  ('prospect', '{project_name}',")
        print(f"   (SELECT id FROM customers WHERE name ILIKE '%{customer_name}%' LIMIT 1),")
        print(f"   '{pipeline_status}', {probability},")
        print(f"   {revenue_est}, '{lead_source}', '{sales_owner}', '{sales_owner}',")
        print(f"   '{notes}', {created_at}){comma}")
    
    print("\nRETURNING id INTO imported_engagements(engagement_id, row_number);")
    
    # Now insert trade breakdowns
    print("\n-- Insert trade breakdowns for each prospect")
    print("DO $$")
    print("DECLARE")
    print("  v_engagement_id UUID;")
    print("  v_trade_id UUID;")
    print("BEGIN")
    
    for i, row in enumerate(rows):
        row_num = i + 1
        project_name = escape_sql(row['Project'])[:50]  # Truncate for comment
        
        print(f"\n  -- Row {row_num}: {project_name}")
        print(f"  SELECT engagement_id INTO v_engagement_id FROM imported_engagements WHERE row_number = {row_num};")
        
        # Insert trades for this engagement
        for csv_col, trade_code in trade_columns.items():
            amount = clean_currency(row.get(csv_col, ''))
            if amount != 'NULL':
                print(f"  ")
                print(f"  SELECT id INTO v_trade_id FROM trades WHERE code = '{trade_code}';")
                print(f"  IF v_trade_id IS NOT NULL THEN")
                print(f"    INSERT INTO engagement_trades (engagement_id, trade_id, estimated_amount)")
                print(f"    VALUES (v_engagement_id, v_trade_id, {amount});")
                print(f"  END IF;")
    
    print("\nEND $$;")

print("""
-- Clean up
DROP FUNCTION IF EXISTS map_pipeline_status(TEXT);

COMMIT;

-- Verification queries:
-- SELECT COUNT(*) FROM engagements WHERE type = 'prospect';
-- SELECT e.name, COUNT(et.id) as trade_count, SUM(et.estimated_amount) as total
-- FROM engagements e
-- LEFT JOIN engagement_trades et ON et.engagement_id = e.id
-- WHERE e.type = 'prospect'
-- GROUP BY e.id, e.name
-- ORDER BY e.name;
""")

