-- Basic schema for staging environment
-- Run this in Supabase SQL Editor for staging database

-- Create projects table
CREATE TABLE public.projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text,
    owner text,
    manager text,
    status text,
    qbid text,
    stage_id bigint,
    sharepoint_folder_url text,
    contract_amount numeric(15,2)
);

-- Create users table
CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text,
    email text UNIQUE,
    role text DEFAULT 'user'::text,
    auth_user_id uuid
);

-- Create contacts table
CREATE TABLE public.contacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text,
    email text,
    phone text,
    company text,
    role text
);

-- Create subcontractors table
CREATE TABLE public.subcontractors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    email text,
    phone text,
    speciality text
);

-- Create basic indexes
CREATE INDEX projects_qbid_idx ON public.projects(qbid);
CREATE INDEX projects_stage_id_idx ON public.projects(stage_id);
CREATE INDEX users_email_idx ON public.users(email);
CREATE INDEX users_auth_user_id_idx ON public.users(auth_user_id);

-- Enable RLS (Row Level Security)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subcontractors ENABLE ROW LEVEL SECURITY;

-- Basic RLS policies (allow all for development)
CREATE POLICY "Allow all operations for authenticated users" ON public.projects
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow all operations for authenticated users" ON public.users
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow all operations for authenticated users" ON public.contacts
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow all operations for authenticated users" ON public.subcontractors
    FOR ALL USING (auth.role() = 'authenticated');